remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

github:
  url: http://ens-labs.com/CS410-rewards-maximizer
  home: /
  bio_url: /team-bio.html
  presentation_url: /presentations.html