remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

github:
  home: http://ens-labs.com/CS410-rewards-maximizer/
  bio_url: http://ens-labs.com/CS410-rewards-maximizer/team-bio.html
  presentation_url: http://ens-labs.com/CS410-rewards-maximizer/presentations.html